spring.application.name=backend-sensor
server.port=8081
# Cria um arquivo chamado 'telemetria' na pasta do projeto
spring.datasource.url=jdbc:h2:file:./data/telemetria
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Garante que a tabela não seja apagada ao reiniciar
spring.jpa.hibernate.ddl-auto=update
